# Generated by Django 5.2.8 on 2025-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreambooks', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
